const jokes = [
    { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything!" },
    { setup: "April showers bring May flowers, but what do May flowers bring?", punchline: "Pilgrims." },
  { setup: "What do you call a fake noodle?", punchline: "An Impasta." },
  { setup: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
  { setup: "What is a funny mountain called?", punchline: "Hill-arious." },
  { setup: "What do you call a song about a tortilla?", punchline: "A wrap." },
  { setup: "What’s Forrest Gump’s password?", punchline: "1forrest1." },
  { setup: "Where do pirates buy hooks?", punchline: "The second hand store." },
  { setup: "Why did the tomato blush?", punchline: "It saw the salad dressing!" },
  { setup: "Why is it bad to iron a four leaf clover?", punchline: "Because you should never press your luck." },
  { setup: "What did one hat say to the other?", punchline: "Wait here, I’m going on ahead!" },
  { setup: "What keys unlock a banana?", punchline: "Mon-keys." },
  { setup: "What is a fancy fish called?", punchline: "So-fish-ticated." },
  { setup: "What’s blue and doesn’t weigh much?", punchline: "Light blue." },
  { setup: "Where do you learn to make a banana split?", punchline: "Sundae school." },
  { setup: "What happened to the frog that parked illegally?", punchline: "It got toad." },
  { setup: "What type of bear is toothless?", punchline: "A gummy bear." },
  { setup: "What cars do eggs drive?", punchline: "A Yolkswagen." },
  { setup: "Why didn’t the skeleton go on the rollercoaster?", punchline: "It didn’t have the guts." },
  { setup: "What did the cereal bring to the bank?", punchline: "Chex." },
  { setup: "How does the moon style his hair?", punchline: "Eclipse it." },
  { setup: "Why did the birds attack the dog?", punchline: "He was pure bread." },
  { setup: "What did one wall say to the other?", punchline: "Let’s meet at the corner." },
  { setup: "Why couldn’t the bicycle stand up alone?", punchline: "Because it was two tired." },
  { setup: "How do you make seven even?", punchline: "Take away the s." },
  { setup: "What’s it called when a snowman throws a tantrum?", punchline: "A meltdown." },
  { setup: "What did the scarecrow win an award for?", punchline: "He was outstanding in his field." },
  { setup: "What cars do sheep drive?", punchline: "Lamborghinis." },
  { setup: "How do cows learn about current events?", punchline: "They read the moo-spaper." },
  { setup: "How do you make a water bed bouncier?", punchline: "Fill it with Poland Spring water." },
  { setup: "Which bear is the most condescending?", punchline: "A pan-duh!" },
  { setup: "What kind of noise does a witch’s vehicle make?", punchline: "Brrrroooom, brrroooom." },
  { setup: "My girlfriend keeps accusing me of cheating. ", punchline: "She's starting to sound like my wife." },
  { setup: "What’s brown and sticky?", punchline: "A stick." },
  { setup: "Two guys walked into a bar.", punchline: " The third guy ducked." },
  { setup: "Did you hear about the actor who broke his leg onstage?", punchline: "He's still in the cast." },
  { setup: "How do you get a country girl’s attention?", punchline: "A tractor." },
  { setup: "What do you call it when a group of apes starts a company?", punchline: "Monkey business." },
  { setup: "Why did the pharmacist walk on her tiptoes?", punchline: "She didn't want to wake the sleeping pills." },
  { setup: "I wanted to buy a pair of camouflage pants,", punchline: " but I couldn't find any." },
  { setup: "Why are elevator jokes so classic and good?", punchline: "They work on many levels." },
  { setup: "I have an inferiority complex, ", punchline: "but it's not a very good one." },
  { setup: "What do you call a pudgy psychic?", punchline: "A four-chin teller." },
  { setup: "I had a date last night and it was perfect. ", punchline: "Tomorrow, I’ll have a fig." },
  { setup: "What did the police officer say to his belly-button?", punchline: "You’re under a vest." },
  { setup: "My wife asked me to stop singing “Wonderwall” to her.'", punchline: "I said 'Maybe..." },
  { setup: "What kind of drink can be bitter and sweet?", punchline: "Reali-tea." },
  { setup: "What do you call a naughty lamb dressed up like a skeleton for Halloween?", punchline: "Baaad to the bone." },
  { setup: "Why did the lobster blush?", punchline: "Because it saw the ocean's bottom!" },
  { setup: "Want to know why nurses like red crayons?", punchline: "Sometimes they have to draw blood." },
  { setup: "What would the Terminator be called in his retirement?", punchline: "The Exterminator." },
  { setup: "What did Tennessee?", punchline: "The same thing as Arkansas." },
  { setup: "My wife asked me to go get 6 cans of Sprite from the grocery store. I realized when I got home that I had picked 7 up.", punchline: "" },
  { setup: "Why do bees have sticky hair?", punchline: "Because they use a honeycomb." },
  { setup: "Why do some couples go to the gym?", punchline: "Because they want their relationship to work out." },
  { setup: "What do you call an angry musician flipping someone off?", punchline: "A song bird." },
  { setup: "What’s the most detail-oriented ocean?", punchline: "The Pacific." },
  { setup: "Why is Peter Pan always flying?", punchline: "Because he Neverlands." },
  { setup: "Which state has the most streets?", punchline: "Rhode Island." },
  { setup: "What do you call 26 letters that went for a swim?", punchline: "Alphawetical." },
  { setup: "What’s the name of a very polite, European body of water?", punchline: "Merci." },
  { setup: "Why was the color green notoriously single?", punchline: "It was always so jaded." },
  { setup: "I used to hate facial hair, but then it grew on me.", punchline: "" },
  { setup: "I want to make a brief joke, but it’s a little cheesy.", punchline: "" },
  { setup: "Why did the coach go to the bank?", punchline: "To get his quarterback." },
  { setup: "How do celebrities stay cool?", punchline: "They have many fans." },
  { setup: "5/4 of people admit they’re bad at fractions.", punchline: "" },
  { setup: "Why did the bedding hide their relationship?", punchline: "They just wanted something pillow-key!" },
  { setup: "You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom?", punchline: "European." },
  { setup: "Dogs can’t operate MRI machines. But catscan.", punchline: "" },
  { setup: "What did the flowers do when the bride walked down the aisle?", punchline: "They rose." },
  { setup: "What do you get from a pampered cow?", punchline: "Spoiled milk." },
  { setup: "What does 'Rockin' Robin' do when she's bored?", punchline: "Tweet." },
  { setup: "Why did Waldo go to therapy?", punchline: "Because he needed to find himself." },
  { setup: "How do you row a canoe filled with puppies?", punchline: "Bring out the doggy paddle." },
  { setup: "Why were the utensils stuck together?", punchline: "They were spooning." },
  { setup: "What's a crafty dancer's favorite hobby?", punchline: "Cutting a rug." },
  { setup: "How does a penguin build his house?", punchline: "Igloos it together." },
  { setup: "What kind of music do chiropractors like?", punchline: "Hip pop." },
  { setup: "Where do you learn to make ice cream?", punchline: "At sundae school." },
  { setup: "What kind of shoes does a lazy person wear?", punchline: "Loafers." },
  { setup: "Why is cold water so insecure?", punchline: "Because it’s never called hot." },
  { setup: "How many apples can you grow on a tree?", punchline: "All of them." },
  { setup: "Why can't you trust an atom?", punchline: "Because they make up everything." },
  { setup: "Why did the baby strawberry cry?", punchline: "Because its mother was in a jam." },
  { setup: "Why couldn't the toilet paper cross the road?", punchline: "Because it got stuck in a crack." },
  { setup: "Stop looking for the perfect match…use a lighter.", punchline: "" },
  { setup: "I told my doctor I heard buzzing, but he said it’s just a bug going around.", punchline: "" },
  { setup: "What kind of car does a sheep like to drive?", punchline: "A Lamborghini." },
  { setup: "What do you call someone who won't stick to a diet?", punchline: "A desserter." },
  { setup: "What did the accountant say while auditing a document?", punchline: "This is taxing." },
  { setup: "What did the two pieces of bread say on their wedding day?", punchline: "It was loaf at first sight." },
  { setup: "Why do melons have weddings?", punchline: "Because they cantaloupe." },
  { setup: "When you have a bladder infection, urine trouble.", punchline: "" },
  { setup: "What did the drummer call his twin daughters?", punchline: "Anna One, Anna Two!" },
  { setup: "What did the juicer say to the orange during self-quarantine?", punchline: "Can’t wait to squeeze you!" },
  { setup: "What do you call a toothless bear?", punchline: "A gummy bear!" },
  { setup: "Want to hear a joke about construction?", punchline: "I’m still working on it." },
  { setup: "Why did the pony ask for a glass of water?", punchline: "Because it was a little horse." },
  { setup: "What's Forrest Gump's password?", punchline: "1forrest1" },
  { setup: "What does a nosey pepper do?", punchline: "It gets jalapeño business." },
  { setup: "How can you mend a broken pumpkin?", punchline: "Use a pumpkin patch." },
  { setup: "Why do dads feel the need to tell such bad jokes?", punchline: "They just want to help you become a groan up." },
  { setup: "Why are spiders so smart?", punchline: "They can find everything on the web." },
  { setup: "What do you call spiders who just got married?", punchline: "Newly-webs." },
  { setup: "What do you call two octopuses that look the same?", punchline: "Itenticle." },
  { setup: "What has one head, one foot, and four legs?", punchline: "A bed." },
  { setup: "What does a house wear?", punchline: "Address." },
  { setup: "Why did the scarecrow win an award?", punchline: "He was out standing in his field." },
  { setup: "What is a scarecrow's favorite fruit?", punchline: "Straw-berries." },
  { setup: "What’s red and smells like blue paint?", punchline: "Red paint." },
  { setup: "How do you know when a chicken is evil?", punchline: "It lays deviled eggs." },
  { setup: "What do you call an unpredictable camera?", punchline: "A loose Canon." },
  { setup: "I didn’t get a haircut, I got them all cut.", punchline: "" },
  { setup: "Which U.S. state is known for its especially small soft drinks?", punchline: "Minnesota." },
  { setup: "What do sprinters eat before a race?", punchline: "Nothing—they fast." },
  { setup: "What did one Dorito farmer say to the other?", punchline: "“Cool Ranch!”" },
  { setup: "How do cows shop?", punchline: "From cattle-logs." },
  { setup: "What do you call a fibbing cat?", punchline: "A lion." },
  { setup: "Why shouldn’t you write with a broken pencil?", punchline: "Because it’s pointless." },
  { setup: "How do you weigh a millennial?", punchline: "In Instagrams." },
  { setup: "What’s the most patriotic sport?", punchline: "Flag football." },
  { setup: "Why were spectators confused by the koala's self-portrait?", punchline: "It was bear." },
  { setup: "Why did the envelope take so long to get ready?", punchline: "It had to get addressed." },
  { setup: "What does a karate master get rewarded with while driving?", punchline: "A seat belt." },
  { setup: "What do you call a baby sheep that knows karate?", punchline: "A lamb chop." },
  { setup: "What did the husband say to his wife right after getting LASIK surgery?", punchline: "\"Aren't you a sight for sore eyes?\"" },
  { setup: "Why are pigs bad drivers?", punchline: "Because they hog the road." },
  { setup: "What do lions use to look at their manes?", punchline: "Mirroars." },
  { setup: "What did the dad say when his golden retriever was caught eating a hot dog?", punchline: "\"It's a dog eat dog world out there.\"" },
  { setup: "Do mascara and lipstick ever argue?", punchline: "Sure, but then they makeup." },
  { setup: "What piece on the playground is always exhausted?", punchline: "The tire swing." },
  { setup: "Why did two tall people get along so well?", punchline: "They could really see eye to eye." },
  { setup: "Why was the gossip disliked at the coffee shop?", punchline: "She always spilled the tea." },
  { setup: "What does a writer have in common with a football player?", punchline: "Anxiety over a rough draft." },
  { setup: "Where do wasps like to get lunch?", punchline: "A bee-stro." },
  { setup: "Is there anything worse than when it's raining cats and dogs?", punchline: "Yes! Hailing taxis." },
  { setup: "Why would doors do well on social media?", punchline: "Everyone looks for their handles." },
  { setup: "Why did the physicist and the biologist break up?", punchline: "Because they had no chemistry." },
  { setup: "If you feel like someone is watching you, you're not alone.", punchline: "" },
  { setup: "Which bathroom appliance would be the worst life preserver?", punchline: "The sink." },
  { setup: "Why was the dad sitting on a pack of playing cards?", punchline: "His kid asked him to sit on the deck." },
  { setup: "How do birds learn how to fly?", punchline: "They wing it!" },
  { setup: "What kind of bird is always getting hurt?", punchline: "The owl." },
  { setup: "What's either a really gross animal issue OR an impressive, magical school?", punchline: "Hogwarts." },
  { setup: "How does Darth Vader like his toast?", punchline: "On the dark side." },
  { setup: "What did the dishwasher say to the oven after a productive day?", punchline: "\"You've been on fire!\"" },
  { setup: "Why did the tomato blush?", punchline: "Because it saw the salad dressing." },
  { setup: "Why did the cashier rip money in half?", punchline: "They were asked to break a bill." },
  { setup: "What did one furniture maker say to another during a tense discussion?", punchline: "\"Let's table this.\"" },
  { setup: "I was going to tell a joke about water, ", punchline: "but it was too tasteless." },
  { setup: "Why couldn't the duck be quiet?", punchline: "Because it was addicted to quack." },
  { setup: "Why was the ghost so tired?", punchline: "He worked the graveyard shift." },
  { setup: "Why do pancakes always win at baseball?", punchline: "They have the best batter." },
  { setup: "Why did the baseball player get arrested?", punchline: "Because he stole second base." },
  { setup: "Why couldn't the couple get married at the library?", punchline: "It was all booked up." },
  { setup: "Why did the pug buy a clock?", punchline: "It wanted to be a watchdog." },
  { setup: "Where do hamburgers go to dance?", punchline: "The meatball." },


];


  
  let timeout;
  
  function displayJoke() {
    const randomIndex = Math.floor(Math.random() * jokes.length);
    const randomJoke = jokes[randomIndex];
    document.getElementById('setup').textContent = randomJoke.setup;
    document.getElementById('punchline').textContent = randomJoke.punchline;
    document.getElementById('punchline').style.display = 'none';
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      document.getElementById('punchline').style.display = 'block';
    }, 15000); // 15 seconds
  }
  
  document.addEventListener('DOMContentLoaded', () => {
    displayJoke();
  
    document.addEventListener('click', () => {
      displayJoke();
    });
  });